# yaml基本语法
# key:与value之间必须有一个空格
person:
  age: 24
  adult: true
  # 注意日期格式默认只支持yyyy/MM/dd格式，其它类型转换应该用类型安全的@Value注解去绑定
  birth: 2020/11/11
  #  map类型也支持行内写法：account: {cbc: "32123",tcb: "45815"}
  # 注意map为<String,Sting>类型时，key设置为中文，或者value设置为数字时都会发生类型转换失败
  account:
    cbc: "32123"
    tcb: "45815"
  # list也支持行内写法：hobbies: [swim,golf,climb]
  hobbies:
    - swim
    - golf
    - climb
  wife:
    name: "lina"
    age: 23
    birth: 2010/10/10
    gender: 女
    email: abc
  name: "张三"

spring:
  #数据库配置 spring:
  datasource:
    url: jdbc:mysql://192.168.116.129:3306/xdb?serverTimezone=GMT&useSSL=true
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
  configuration.map-underscore-to-camel-case: true
