##jwt配置
webtoken:
  # 代表这个JWT的接收对象,存入webToken
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  issuer: restapiuser
  # 过期时间，时间戳（10分钟）
  expireTime: 600000